"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, ChevronLeft, ChevronRight, FileText, Image as ImageIcon, X } from "lucide-react";
import Button from "@/components/ui/Button";
import api from "@/lib/api";
import { invalidateEntityArtwork } from "@/hooks/useAttachment";
import { optimizeImage } from "@/lib/media/image-optimization";

const STEPS = ["Release", "Artists", "Tracks", "Artwork", "Contracts", "Review"];
const listItems = (response) => { const value = response?.data; return Array.isArray(value) ? value : Array.isArray(value?.items) ? value.items : []; };
const errorMessage = (err, fallback) => { const value = err?.response?.data?.error ?? err?.message; return typeof value === "string" && value.trim() ? value : fallback; };
const Field = ({ label, children, hint }) => <div className="space-y-1.5"><label className="text-xs font-bold text-text-secondary">{label}</label>{children}{hint ? <p className="text-[11px] text-text-secondary">{hint}</p> : null}</div>;
const SelectableRow = ({ selected, onClick, title, subtitle, badge }) => <button type="button" onClick={onClick} className={`w-full rounded-xl border p-3 text-left transition-colors ${selected ? "border-accent bg-accent/10" : "border-border bg-surface hover:bg-surface-elevated"}`}><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="truncate text-sm font-semibold">{title}</div>{subtitle ? <div className="truncate text-xs text-text-secondary">{subtitle}</div> : null}</div><div className="flex shrink-0 items-center gap-2">{badge ? <span className="rounded-full border border-border px-2 py-0.5 text-[10px] text-text-secondary">{badge}</span> : null}{selected ? <Check size={16} className="text-accent" /> : null}</div></div></button>;

export default function ReleaseCreationWizard({ isOpen, onClose, onCreated }) {
  const [step, setStep] = useState(0); const [releaseId, setReleaseId] = useState(null); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const [artists, setArtists] = useState([]); const [tracks, setTracks] = useState([]); const [contracts, setContracts] = useState([]); const [labels, setLabels] = useState([]); const [distributors, setDistributors] = useState([]);
  const [artwork, setArtwork] = useState(null); const [linkedContractIds, setLinkedContractIds] = useState([]); const [selectedArtistIds, setSelectedArtistIds] = useState([]); const [selectedTrackIds, setSelectedTrackIds] = useState([]); const [moveTrackIds, setMoveTrackIds] = useState([]);
  const [release, setRelease] = useState({ title: "", release_type: "Single", release_date: "", catalog_number: "", upc_code: "", label_id: "", distributor_id: "", streaming_link: "" });

  useEffect(() => {
    if (!isOpen) return;
    setStep(0); setReleaseId(null); setSaving(false); setError(""); setArtwork(null); setLinkedContractIds([]); setSelectedArtistIds([]); setSelectedTrackIds([]); setMoveTrackIds([]);
    setRelease({ title: "", release_type: "Single", release_date: "", catalog_number: "", upc_code: "", label_id: "", distributor_id: "", streaming_link: "" });
    Promise.all([api.get("/artists"), api.get("/tracks"), api.get("/contracts"), api.get("/labels"), api.get("/network/organizations")]).then(([a, t, c, l, d]) => { setArtists(listItems(a)); setTracks(listItems(t)); setContracts(listItems(c)); setLabels(listItems(l)); setDistributors(listItems(d)); }).catch((err) => console.error("Release wizard reference data failed", err));
  }, [isOpen]);

  const selectedArtists = useMemo(() => artists.filter((a) => selectedArtistIds.includes(a.id)), [artists, selectedArtistIds]);
  const selectedTracks = useMemo(() => tracks.filter((t) => selectedTrackIds.includes(t.id)), [tracks, selectedTrackIds]);
  const selectedContracts = useMemo(() => contracts.filter((c) => linkedContractIds.includes(c.id)), [contracts, linkedContractIds]);

  const createDraft = async () => {
    if (!release.title.trim()) { setError("Release title is required."); return null; }
    setSaving(true); setError("");
    try {
      const payload = { ...release, release_date: release.release_date || undefined, catalog_number: release.catalog_number || undefined, upc_code: release.upc_code || undefined, label_id: release.label_id ? Number(release.label_id) : undefined, distributor_id: release.distributor_id ? Number(release.distributor_id) : undefined, streaming_link: release.streaming_link || undefined, status: "draft" };
      const response = await api.post("/releases", payload); setReleaseId(response.data.id); return response.data.id;
    } catch (err) { setError(errorMessage(err, "Failed to create release draft.")); return null; } finally { setSaving(false); }
  };
  const updateRelease = async (payload) => { if (!releaseId) return false; setSaving(true); setError(""); try { await api.put(`/releases?id=${releaseId}`, payload); return true; } catch (err) { setError(errorMessage(err, "Failed to save release changes.")); return false; } finally { setSaving(false); } };
  const uploadArtwork = async () => {
    if (!artwork || !releaseId) return true; setSaving(true); setError("");
    try { const optimized = await optimizeImage(artwork, "artwork"); const response = await api.post("/storage/upload-url", { entityType: "release", entityId: String(releaseId), fileName: optimized.name, mimeType: optimized.type, fileSize: optimized.size, folder: "releases" }); const upload = response.data; const r2 = await fetch(upload.uploadUrl, { method: "PUT", headers: { "Content-Type": optimized.type }, body: optimized }); if (!r2.ok) throw new Error(`R2 upload failed (${r2.status})`); await api.post("/storage/complete", { entityType: "release", entityId: String(releaseId), key: upload.key, fileName: upload.fileName, originalName: artwork.name, mimeType: optimized.type, fileSize: optimized.size }); invalidateEntityArtwork("release", releaseId); return true; }
    catch (err) { setError(errorMessage(err, "Failed to upload release artwork.")); return false; } finally { setSaving(false); }
  };
  const linkContracts = async () => { if (!releaseId) return true; for (const contractId of linkedContractIds) { try { await api.post("/contracts?action=add_asset", { id: contractId, asset_type: "Release", asset_id: releaseId }); } catch (err) { const message = errorMessage(err, "Failed to link contract."); if (!message.toLowerCase().includes("already")) { setError(message); return false; } } } return true; };
  const next = async () => { setError(""); if (step === 0) { if (!(releaseId || await createDraft())) return; } else if (step === 1) { if (!(await updateRelease({ artist_ids: selectedArtistIds }))) return; } else if (step === 2) { if (!(await updateRelease({ track_ids: selectedTrackIds, move_track_ids: moveTrackIds }))) return; } else if (step === 3) { if (!(await uploadArtwork())) return; } else if (step === 4) { if (!(await linkContracts())) return; } if (step < STEPS.length - 1) setStep((value) => value + 1); };
  const toggleTrack = (track) => { const selected = selectedTrackIds.includes(track.id); setSelectedTrackIds((ids) => selected ? ids.filter((id) => id !== track.id) : [...ids, track.id]); setMoveTrackIds((ids) => selected ? ids.filter((id) => id !== track.id) : track.release_id ? [...ids, track.id] : ids); };
  if (!isOpen) return null;

  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#0f1115]/80 p-4 backdrop-blur-md" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}>
    <div className="flex max-h-[92vh] w-full max-w-3xl flex-col overflow-hidden rounded-3xl border border-white/10 bg-premium-glass shadow-glass">
      <div className="flex items-center justify-between border-b border-white/5 bg-white/[0.02] p-6"><div><h2 className="text-xl font-black tracking-tight text-white">New Release</h2><p className="mt-1 text-xs text-text-secondary">Guided setup · {STEPS[step]}</p></div><button type="button" onClick={onClose} className="flex h-8 w-8 items-center justify-center rounded-full bg-white/5 text-text-secondary hover:bg-white/10 hover:text-white"><X size={16} /></button></div>
      <div className="border-b border-white/5 px-6 py-4"><div className="grid grid-cols-6 gap-1">{STEPS.map((label, index) => <button key={label} type="button" onClick={() => index <= step && setStep(index)} className="text-center"><div className={`mb-2 h-1 rounded-full ${index <= step ? "bg-accent" : "bg-border"}`} /><span className={`text-[10px] font-semibold ${index <= step ? "text-text-primary" : "text-text-secondary"}`}>{label}</span></button>)}</div></div>
      <div className="flex-1 overflow-y-auto p-6 custom-scrollbar">{error ? <div className="mb-5 rounded-xl border border-danger/20 bg-danger/10 p-3 text-sm text-danger">{error}</div> : null}
        {step === 0 ? <div className="space-y-5"><div><h3 className="text-lg font-bold">Start with the release identity</h3><p className="text-sm text-text-secondary">Enter the metadata you know now. The release becomes a draft while you complete the setup.</p></div><Field label="Release title *"><input className="input w-full" autoFocus value={release.title} onChange={(e) => setRelease({ ...release, title: e.target.value })} /></Field><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Field label="Release type"><select className="input w-full" value={release.release_type} onChange={(e) => setRelease({ ...release, release_type: e.target.value })}><option>Single</option><option>EP</option><option>Album</option><option>Compilation</option></select></Field><Field label="Release date"><input className="input w-full" type="date" value={release.release_date} onChange={(e) => setRelease({ ...release, release_date: e.target.value })} /></Field><Field label="Catalog number"><input className="input w-full" value={release.catalog_number} onChange={(e) => setRelease({ ...release, catalog_number: e.target.value })} /></Field><Field label="UPC"><input className="input w-full" value={release.upc_code} onChange={(e) => setRelease({ ...release, upc_code: e.target.value })} /></Field></div><Field label="Label"><select className="input w-full" value={release.label_id} onChange={(e) => setRelease({ ...release, label_id: e.target.value })}><option value="">Select a label</option>{labels.map((label) => <option key={label.id} value={label.id}>{label.name}</option>)}</select></Field><Field label="Distributor"><select className="input w-full" value={release.distributor_id} onChange={(e) => setRelease({ ...release, distributor_id: e.target.value })}><option value="">Select a distributor</option>{distributors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Streaming link"><input className="input w-full" type="url" value={release.streaming_link} onChange={(e) => setRelease({ ...release, streaming_link: e.target.value })} placeholder="https://..." /></Field></div> : null}
        {step === 1 ? <div className="space-y-4"><div><h3 className="text-lg font-bold">Add artists</h3><p className="text-sm text-text-secondary">Select the artists attached to this release.</p></div><div className="max-h-80 space-y-2 overflow-y-auto">{artists.map((artist) => <SelectableRow key={artist.id} selected={selectedArtistIds.includes(artist.id)} onClick={() => setSelectedArtistIds((ids) => ids.includes(artist.id) ? ids.filter((id) => id !== artist.id) : [...ids, artist.id])} title={artist.display_name || artist.stage_name || artist.name} subtitle={artist.display_name || artist.stage_name ? artist.name : undefined} />)}{!artists.length ? <p className="py-8 text-center text-sm text-text-secondary">No artists available.</p> : null}</div><p className="text-xs text-text-secondary">{selectedArtists.length} selected.</p></div> : null}
        {step === 2 ? <div className="space-y-4"><div><h3 className="text-lg font-bold">Build the tracklist</h3><p className="text-sm text-text-secondary">Select tracks already in the catalog. Existing Primary Releases are shown explicitly.</p></div><div className="max-h-80 space-y-2 overflow-y-auto">{tracks.map((track) => <SelectableRow key={track.id} selected={selectedTrackIds.includes(track.id)} onClick={() => toggleTrack(track)} title={track.title} subtitle={track.isrc_code || track.genre || "No ISRC"} badge={track.release_id ? (selectedTrackIds.includes(track.id) ? "Move Primary" : "Has Primary") : "Unassigned"} />)}{!tracks.length ? <p className="py-8 text-center text-sm text-text-secondary">No tracks available.</p> : null}</div><p className="text-xs text-text-secondary">{selectedTracks.length} selected · {moveTrackIds.length} primary moves.</p></div> : null}
        {step === 3 ? <div className="space-y-5"><div><h3 className="text-lg font-bold">Add artwork</h3><p className="text-sm text-text-secondary">Artwork is compressed in the browser before direct upload to R2. Maximum stored artwork size is 1.5 MB.</p></div><label className="flex min-h-56 cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed border-border bg-surface hover:bg-surface-elevated"><ImageIcon size={40} className="mb-3 text-text-secondary" /><span className="text-sm font-semibold">{artwork ? artwork.name : "Choose artwork"}</span><span className="mt-1 text-xs text-text-secondary">JPEG, PNG or WebP · optimized automatically</span><input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(e) => setArtwork(e.target.files?.[0] || null)} /></label>{artwork ? <div className="flex items-center justify-between rounded-xl border border-border p-3 text-xs"><span>{artwork.name} · {(artwork.size / 1024 / 1024).toFixed(2)} MB source</span><button type="button" onClick={() => setArtwork(null)}><X size={15} /></button></div> : null}<p className="text-xs text-text-secondary">Artwork is optional.</p></div> : null}
        {step === 4 ? <div className="space-y-4"><div><h3 className="text-lg font-bold">Link contracts</h3><p className="text-sm text-text-secondary">Attach existing contracts to this release.</p></div><div className="max-h-80 space-y-2 overflow-y-auto">{contracts.map((contract) => <SelectableRow key={contract.id} selected={linkedContractIds.includes(contract.id)} onClick={() => setLinkedContractIds((ids) => ids.includes(contract.id) ? ids.filter((id) => id !== contract.id) : [...ids, contract.id])} title={contract.title || contract.contract_number || `Contract ${contract.id}`} subtitle={contract.contract_number || contract.type || "Contract"} />)}{!contracts.length ? <p className="py-8 text-center text-sm text-text-secondary">No existing contracts available.</p> : null}</div><p className="text-xs text-text-secondary">{selectedContracts.length} selected.</p></div> : null}
        {step === 5 ? <div className="space-y-5"><div><h3 className="text-lg font-bold">Review and finish</h3><p className="text-sm text-text-secondary">The release remains a draft. Finish takes you to the release detail page.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{[["Title", release.title || "—"],["Type", release.release_type],["Date", release.release_date || "TBA"],["Catalog #", release.catalog_number || "—"],["Artists", String(selectedArtists.length)],["Tracks", String(selectedTracks.length)],["Artwork", artwork ? "Selected" : "Not added"],["Contracts", String(selectedContracts.length)],["Status", "Draft"]].map(([label, value]) => <div key={label} className="rounded-xl border border-border bg-surface p-3"><div className="text-[10px] font-bold uppercase tracking-wider text-text-secondary">{label}</div><div className="mt-1 truncate text-sm font-semibold">{value}</div></div>)}</div><div className="rounded-xl border border-border bg-surface p-4 text-sm text-text-secondary"><div className="mb-2 flex items-center gap-2 text-text-primary"><FileText size={15} /> Draft saved</div><p>Continue managing the release from its detail page.</p></div></div> : null}
      </div>
      <div className="flex items-center justify-between border-t border-white/5 bg-white/[0.02] p-6"><Button type="button" variant="secondary" disabled={step === 0 || saving} onClick={() => setStep((value) => Math.max(0, value - 1))}><ChevronLeft size={15} />Back</Button>{step < STEPS.length - 1 ? <Button type="button" disabled={saving} loading={saving} onClick={next}>{step === 0 ? "Create Draft & Continue" : "Save & Continue"}<ChevronRight size={15} /></Button> : <Button type="button" onClick={() => { const id = releaseId; onClose(); if (id) onCreated?.(id); }}><Check size={15} />Finish Release Setup</Button>}</div>
    </div>
  </div>;
}
