"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, ChevronLeft, ChevronRight, FileText, Image as ImageIcon, Plus, Search, X } from "lucide-react";
import Button from "@/components/ui/Button";
import AddContractWizard from "@/components/contracts/AddContractWizard";
import api from "@/lib/api";
import { invalidateEntityArtwork } from "@/hooks/useAttachment";
import { optimizeImage } from "@/lib/media/image-optimization";

const STEPS = ["Release", "Artists", "Tracks", "Artwork", "Contracts", "Review"];
const items = (r) => Array.isArray(r?.data) ? r.data : Array.isArray(r?.data?.items) ? r.data.items : [];
const message = (e, fallback) => { const value = e?.response?.data?.error ?? e?.message; return typeof value === "string" && value.trim() ? value : fallback; };
const Field = ({ label, children }) => <div className="space-y-1.5"><label className="text-xs font-bold text-text-secondary">{label}</label>{children}</div>;
const SearchBox = ({ value, onChange, placeholder }) => <div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-text-secondary" /><input className="input w-full pl-9" value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} /></div>;
const Row = ({ selected, onClick, title, subtitle, badge }) => <button type="button" onClick={onClick} className={`w-full rounded-xl border p-3 text-left ${selected ? "border-accent bg-accent/10" : "border-border bg-surface hover:bg-surface-elevated"}`}><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="truncate text-sm font-semibold">{title}</div>{subtitle ? <div className="truncate text-xs text-text-secondary">{subtitle}</div> : null}</div>{selected ? <Check size={16} className="shrink-0 text-accent" /> : badge ? <span className="shrink-0 rounded-full border border-border px-2 py-0.5 text-[10px] text-text-secondary">{badge}</span> : null}</div></button>;
const Chips = ({ values, label, onRemove }) => values.length ? <div className="flex flex-wrap gap-2">{values.map((v) => <span key={v.id} className="inline-flex items-center gap-1 rounded-full border border-accent/30 bg-accent/10 px-2.5 py-1 text-xs font-semibold">{label(v)}<button type="button" onClick={() => onRemove(v.id)}><X size={12} /></button></span>)}</div> : null;

export default function ReleaseCreationWizard({ isOpen, onClose, onCreated }) {
  const [step, setStep] = useState(0), [releaseId, setReleaseId] = useState(null), [saving, setSaving] = useState(false), [error, setError] = useState("");
  const [artists, setArtists] = useState([]), [tracks, setTracks] = useState([]), [contracts, setContracts] = useState([]), [labels, setLabels] = useState([]), [distributors, setDistributors] = useState([]);
  const [artistQ, setArtistQ] = useState(""), [trackQ, setTrackQ] = useState(""), [contractQ, setContractQ] = useState("");
  const [selectedArtistIds, setSelectedArtistIds] = useState([]), [selectedTrackIds, setSelectedTrackIds] = useState([]), [moveTrackIds, setMoveTrackIds] = useState([]), [contractIds, setContractIds] = useState([]);
  const [artwork, setArtwork] = useState(null), [artistModal, setArtistModal] = useState(false), [trackModal, setTrackModal] = useState(false), [contractModal, setContractModal] = useState(false);
  const [newArtist, setNewArtist] = useState({ name: "", aka: "" }), [newTrack, setNewTrack] = useState({ title: "", isrc_code: "" });
  const [release, setRelease] = useState({ title: "", release_type: "Single", release_date: "", catalog_number: "", upc_code: "", label_id: "", distributor_id: "", streaming_link: "" });

  useEffect(() => {
    if (!isOpen) return;
    setStep(0); setReleaseId(null); setSaving(false); setError(""); setArtistQ(""); setTrackQ(""); setContractQ(""); setSelectedArtistIds([]); setSelectedTrackIds([]); setMoveTrackIds([]); setContractIds([]); setArtwork(null); setArtistModal(false); setTrackModal(false); setContractModal(false); setNewArtist({ name: "", aka: "" }); setNewTrack({ title: "", isrc_code: "" });
    setRelease({ title: "", release_type: "Single", release_date: "", catalog_number: "", upc_code: "", label_id: "", distributor_id: "", streaming_link: "" });
    Promise.all([api.get("/artists?limit=100"), api.get("/tracks?limit=100"), api.get("/contracts?limit=100"), api.get("/labels"), api.get("/network/organizations")]).then(([a,t,c,l,d]) => { setArtists(items(a)); setTracks(items(t)); setContracts(items(c)); setLabels(items(l)); setDistributors(items(d)); }).catch((e) => console.error("Release wizard reference data failed", e));
  }, [isOpen]);

  useEffect(() => { if (!isOpen || artistQ.trim().length < 2) return; const timer = setTimeout(async () => { try { setArtists(items(await api.get(`/artists?q=${encodeURIComponent(artistQ.trim())}&limit=20`))); } catch (e) { console.error(e); } }, 250); return () => clearTimeout(timer); }, [artistQ, isOpen]);
  useEffect(() => { if (!isOpen || trackQ.trim().length < 2) return; const timer = setTimeout(async () => { try { setTracks(items(await api.get(`/tracks?q=${encodeURIComponent(trackQ.trim())}&limit=20`))); } catch (e) { console.error(e); } }, 250); return () => clearTimeout(timer); }, [trackQ, isOpen]);
  useEffect(() => { if (!isOpen || contractQ.trim().length < 2) return; const timer = setTimeout(async () => { try { setContracts(items(await api.get(`/contracts/search?q=${encodeURIComponent(contractQ.trim())}&limit=20`))); } catch (e) { console.error(e); } }, 250); return () => clearTimeout(timer); }, [contractQ, isOpen]);

  const selectedArtists = useMemo(() => artists.filter((x) => selectedArtistIds.includes(x.id)), [artists, selectedArtistIds]);
  const selectedTracks = useMemo(() => tracks.filter((x) => selectedTrackIds.includes(x.id)), [tracks, selectedTrackIds]);
  const selectedContracts = useMemo(() => contracts.filter((x) => contractIds.includes(x.id)), [contracts, contractIds]);
  const visibleArtists = useMemo(() => artistQ.trim() ? artists : artists.slice(0,20), [artists, artistQ]);
  const visibleTracks = useMemo(() => trackQ.trim() ? tracks : tracks.slice(0,20), [tracks, trackQ]);
  const visibleContracts = useMemo(() => contractQ.trim() ? contracts : contracts.slice(0,20), [contracts, contractQ]);

  const createRelease = async () => { if (!release.title.trim()) { setError("Release title is required."); return null; } setSaving(true); setError(""); try { const r = await api.post("/releases", { ...release, release_date: release.release_date || undefined, catalog_number: release.catalog_number || undefined, upc_code: release.upc_code || undefined, label_id: release.label_id ? Number(release.label_id) : undefined, distributor_id: release.distributor_id ? Number(release.distributor_id) : undefined, streaming_link: release.streaming_link || undefined, status: "draft" }); setReleaseId(r.data.id); return r.data.id; } catch (e) { setError(message(e, "Failed to create release.")); return null; } finally { setSaving(false); } };
  const updateRelease = async (payload) => { if (!releaseId) return false; setSaving(true); setError(""); try { await api.put(`/releases?id=${releaseId}`, payload); return true; } catch (e) { setError(message(e, "Failed to save release changes.")); return false; } finally { setSaving(false); } };
  const uploadArtwork = async () => { if (!artwork || !releaseId) return true; setSaving(true); setError(""); try { const optimized = await optimizeImage(artwork, "artwork"); const r = await api.post("/storage/upload-url", { entityType: "release", entityId: String(releaseId), fileName: optimized.name, mimeType: optimized.type, fileSize: optimized.size, folder: "release" }); const upload = r.data; const put = await fetch(upload.uploadUrl, { method: "PUT", headers: { "Content-Type": optimized.type }, body: optimized }); if (!put.ok) throw new Error(`R2 upload failed (${put.status})`); await api.post("/storage/complete", { entityType: "release", entityId: String(releaseId), key: upload.key, fileName: upload.fileName, originalName: artwork.name, mimeType: optimized.type, fileSize: optimized.size }); invalidateEntityArtwork("release", releaseId); return true; } catch (e) { setError(message(e, "Failed to upload release artwork.")); return false; } finally { setSaving(false); } };
  const linkContracts = async () => { if (!releaseId) return true; for (const id of contractIds) { try { await api.post("/contracts/link-release", { contract_id: id, release_id: releaseId }); } catch (e) { setError(message(e, "Failed to link contract.")); return false; } } return true; };
  const next = async () => { setError(""); if (step === 0 && !(releaseId || await createRelease())) return; if (step === 1 && !(await updateRelease({ artist_ids: selectedArtistIds }))) return; if (step === 2 && !(await updateRelease({ track_ids: selectedTrackIds, move_track_ids: moveTrackIds }))) return; if (step === 3 && !(await uploadArtwork())) return; if (step === 4 && !(await linkContracts())) return; if (step < 5) setStep((s) => s + 1); };
  const toggleTrack = (track) => { const selected = selectedTrackIds.includes(track.id); setSelectedTrackIds((ids) => selected ? ids.filter((id) => id !== track.id) : [...ids, track.id]); setMoveTrackIds((ids) => selected ? ids.filter((id) => id !== track.id) : track.release_id ? [...ids, track.id] : ids); };
  const createArtist = async () => { if (!newArtist.name.trim()) { setError("Artist legal name is required."); return; } setSaving(true); setError(""); try { const r = await api.post("/artists", { name: newArtist.name.trim(), aka: newArtist.aka.trim() || undefined }); setArtists((xs) => [r.data, ...xs]); setSelectedArtistIds((ids) => [...ids, r.data.id]); setArtistModal(false); setNewArtist({ name: "", aka: "" }); } catch (e) { setError(message(e, "Failed to create artist.")); } finally { setSaving(false); } };
  const createTrack = async () => { if (!newTrack.title.trim()) { setError("Track title is required."); return; } setSaving(true); setError(""); try { const r = await api.post("/tracks", { title: newTrack.title.trim(), isrc_code: newTrack.isrc_code.trim() || undefined, artist_ids: selectedArtistIds }); setTracks((xs) => [r.data, ...xs]); setSelectedTrackIds((ids) => [...ids, r.data.id]); setTrackModal(false); setNewTrack({ title: "", isrc_code: "" }); } catch (e) { setError(message(e, "Failed to create track.")); } finally { setSaving(false); } };
  const attachCreatedContract = (contract) => { if (contract?.id) { setContracts((xs) => [contract, ...xs.filter((x) => x.id !== contract.id)]); setContractIds((ids) => ids.includes(contract.id) ? ids : [...ids, contract.id]); } setContractModal(false); };
  if (!isOpen) return null;

  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#0f1115]/80 p-4 backdrop-blur-md" onMouseDown={(e) => e.target === e.currentTarget && onClose()}>
    <div className="flex max-h-[92vh] w-full max-w-3xl flex-col overflow-hidden rounded-3xl border border-white/10 bg-premium-glass shadow-glass">
      <header className="flex items-center justify-between border-b border-white/5 bg-white/[0.02] p-6"><div><h2 className="text-xl font-black tracking-tight text-white">New Release</h2><p className="mt-1 text-xs text-text-secondary">Guided setup · {STEPS[step]}</p></div><button type="button" onClick={onClose}><X size={16}/></button></header>
      <div className="border-b border-white/5 px-6 py-4"><div className="grid grid-cols-6 gap-1">{STEPS.map((s,i)=><button key={s} type="button" onClick={()=>i<=step&&setStep(i)}><div className={`mb-2 h-1 rounded-full ${i<=step?"bg-accent":"bg-border"}`} /><span className={`text-[10px] font-semibold ${i<=step?"text-text-primary":"text-text-secondary"}`}>{s}</span></button>)}</div></div>
      <main className="flex-1 overflow-y-auto p-6 custom-scrollbar">{error ? <div className="mb-5 rounded-xl border border-danger/20 bg-danger/10 p-3 text-sm text-danger">{error}</div> : null}
        {step===0&&<div className="space-y-5"><div><h3 className="text-lg font-bold">Start with the release identity</h3><p className="text-sm text-text-secondary">Enter the metadata you know now. You can complete the remaining setup in this flow.</p></div><Field label="Release title *"><input className="input w-full" autoFocus value={release.title} onChange={e=>setRelease({...release,title:e.target.value})}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Release type"><select className="input w-full" value={release.release_type} onChange={e=>setRelease({...release,release_type:e.target.value})}><option>Single</option><option>EP</option><option>Album</option><option>Compilation</option></select></Field><Field label="Release date"><input className="input w-full" type="date" value={release.release_date} onChange={e=>setRelease({...release,release_date:e.target.value})}/></Field><Field label="Catalog number"><input className="input w-full" value={release.catalog_number} onChange={e=>setRelease({...release,catalog_number:e.target.value})}/></Field><Field label="UPC"><input className="input w-full" value={release.upc_code} onChange={e=>setRelease({...release,upc_code:e.target.value})}/></Field></div><Field label="Label"><select className="input w-full" value={release.label_id} onChange={e=>setRelease({...release,label_id:e.target.value})}><option value="">Select a label</option>{labels.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Distributor"><select className="input w-full" value={release.distributor_id} onChange={e=>setRelease({...release,distributor_id:e.target.value})}><option value="">Select a distributor</option>{distributors.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Streaming link"><input className="input w-full" type="url" value={release.streaming_link} onChange={e=>setRelease({...release,streaming_link:e.target.value})} placeholder="https://..."/></Field></div>}
        {step===1&&<div className="space-y-4"><div><h3 className="text-lg font-bold">Add artists</h3><p className="text-sm text-text-secondary">Search the catalog and select artists. Create a new artist without leaving this screen.</p></div><div className="flex gap-2"><div className="flex-1"><SearchBox value={artistQ} onChange={setArtistQ} placeholder="Search by stage name or legal name"/></div><Button type="button" variant="secondary" onClick={()=>setArtistModal(true)}><Plus size={15}/>New Artist</Button></div><Chips values={selectedArtists} label={x=>x.display_name||x.aka||x.name} onRemove={id=>setSelectedArtistIds(xs=>xs.filter(x=>x!==id))}/><div className="max-h-72 space-y-2 overflow-y-auto">{visibleArtists.map(x=><Row key={x.id} selected={selectedArtistIds.includes(x.id)} onClick={()=>setSelectedArtistIds(xs=>xs.includes(x.id)?xs.filter(id=>id!==x.id):[...xs,x.id])} title={x.display_name||x.aka||x.name} subtitle={x.display_name||x.aka?x.name:undefined}/>)}</div>{!visibleArtists.length&&<p className="py-8 text-center text-sm text-text-secondary">No artist found. Use New Artist.</p>}<p className="text-xs text-text-secondary">{selectedArtistIds.length} selected.</p></div>}
        {step===2&&<div className="space-y-4"><div><h3 className="text-lg font-bold">Build the tracklist</h3><p className="text-sm text-text-secondary">Search the catalog instead of scrolling through the full track library. Create a new track here when needed.</p></div><div className="flex gap-2"><div className="flex-1"><SearchBox value={trackQ} onChange={setTrackQ} placeholder="Search track title or ISRC"/></div><Button type="button" variant="secondary" onClick={()=>setTrackModal(true)}><Plus size={15}/>New Track</Button></div><Chips values={selectedTracks} label={x=>x.title} onRemove={id=>{setSelectedTrackIds(xs=>xs.filter(x=>x!==id));setMoveTrackIds(xs=>xs.filter(x=>x!==id));}}/><div className="max-h-72 space-y-2 overflow-y-auto">{visibleTracks.map(x=><Row key={x.id} selected={selectedTrackIds.includes(x.id)} onClick={()=>toggleTrack(x)} title={x.title} subtitle={x.isrc_code||x.genre||"No ISRC"} badge={x.release_id?(selectedTrackIds.includes(x.id)?"Move Primary":"Has Primary"):"Unassigned"}/>)}</div>{!visibleTracks.length&&<p className="py-8 text-center text-sm text-text-secondary">No track found. Use New Track.</p>}<p className="text-xs text-text-secondary">{selectedTrackIds.length} selected · {moveTrackIds.length} primary moves.</p></div>}
        {step===3&&<div className="space-y-5"><div><h3 className="text-lg font-bold">Add artwork</h3><p className="text-sm text-text-secondary">Artwork is compressed in the browser before direct upload to R2. Maximum stored artwork size is 1.5 MB.</p></div><label className="flex min-h-56 cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed border-border bg-surface hover:bg-surface-elevated"><ImageIcon size={40} className="mb-3 text-text-secondary"/><span className="text-sm font-semibold">{artwork?artwork.name:"Choose artwork"}</span><span className="mt-1 text-xs text-text-secondary">JPEG, PNG or WebP · optimized automatically</span><input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>setArtwork(e.target.files?.[0]||null)}/></label>{artwork&&<div className="flex items-center justify-between rounded-xl border border-border p-3 text-xs"><span>{artwork.name} · {(artwork.size/1024/1024).toFixed(2)} MB source</span><button type="button" onClick={()=>setArtwork(null)}><X size={15}/></button></div>}<p className="text-xs text-text-secondary">Artwork is optional.</p></div>}
        {step===4&&<div className="space-y-4"><div><h3 className="text-lg font-bold">Link contracts</h3><p className="text-sm text-text-secondary">Search an existing contract or create a new contract intake here. A newly created contract is saved to the Contracts workspace and linked to this release.</p></div><div className="flex gap-2"><div className="flex-1"><SearchBox value={contractQ} onChange={setContractQ} placeholder="Search contract title, number or type"/></div><Button type="button" variant="secondary" onClick={()=>setContractModal(true)}><Plus size={15}/>New Contract</Button></div><Chips values={selectedContracts} label={x=>x.title||x.contract_number||`Contract ${x.id}`} onRemove={id=>setContractIds(xs=>xs.filter(x=>x!==id))}/><div className="max-h-72 space-y-2 overflow-y-auto">{visibleContracts.map(x=><Row key={x.id} selected={contractIds.includes(x.id)} onClick={()=>setContractIds(xs=>xs.includes(x.id)?xs.filter(id=>id!==x.id):[...xs,x.id])} title={x.title||x.contract_number||`Contract ${x.id}`} subtitle={x.contract_number||x.type||"Contract"}/>)}</div>{!visibleContracts.length&&<p className="py-8 text-center text-sm text-text-secondary">No contract found. Use New Contract to start a contract intake.</p>}<p className="text-xs text-text-secondary">{contractIds.length} selected.</p></div>}
        {step===5&&<div className="space-y-5"><div><h3 className="text-lg font-bold">Review and finish</h3><p className="text-sm text-text-secondary">Review the setup before opening the release detail page.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{[["Title",release.title||"—"],["Type",release.release_type],["Date",release.release_date||"TBA"],["Catalog #",release.catalog_number||"—"],["Artists",selectedArtistIds.length],["Tracks",selectedTrackIds.length],["Artwork",artwork?"Selected":"Not added"],["Contracts",contractIds.length]].map(([k,v])=><div key={k} className="rounded-xl border border-border bg-surface p-3"><div className="text-[10px] font-bold uppercase tracking-wider text-text-secondary">{k}</div><div className="mt-1 truncate text-sm font-semibold">{v}</div></div>)}</div><div className="rounded-xl border border-border bg-surface p-4 text-sm text-text-secondary"><div className="mb-2 flex items-center gap-2 text-text-primary"><FileText size={15}/>Setup saved</div><p>The release is ready for continued management from its detail page.</p></div></div>}
      </main>
      <footer className="flex items-center justify-between border-t border-white/5 bg-white/[0.02] p-6"><Button type="button" variant="secondary" disabled={step===0||saving} onClick={()=>setStep(s=>Math.max(0,s-1))}><ChevronLeft size={15}/>Back</Button>{step<5?<Button type="button" disabled={saving} loading={saving} onClick={next}>{step===0?"Create & Continue":"Save & Continue"}<ChevronRight size={15}/></Button>:<Button type="button" onClick={()=>{const id=releaseId;onClose();if(id)onCreated?.(id);}}><Check size={15}/>Finish Release Setup</Button>}</footer>
    </div>
    {artistModal&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 p-4" onMouseDown={e=>e.target===e.currentTarget&&setArtistModal(false)}><div className="w-full max-w-md rounded-2xl border border-border bg-surface p-5 shadow-2xl"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-bold">Create artist</h3><p className="text-xs text-text-secondary">Add the artist without leaving release setup.</p></div><button type="button" onClick={()=>setArtistModal(false)}><X size={16}/></button></div><div className="space-y-4"><Field label="Legal name *"><input className="input w-full" autoFocus value={newArtist.name} onChange={e=>setNewArtist({...newArtist,name:e.target.value})}/></Field><Field label="Stage name / AKA"><input className="input w-full" value={newArtist.aka} onChange={e=>setNewArtist({...newArtist,aka:e.target.value})}/></Field></div><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>setArtistModal(false)}>Cancel</Button><Button type="button" loading={saving} disabled={saving} onClick={createArtist}>Create Artist</Button></div></div></div>}
    {trackModal&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 p-4" onMouseDown={e=>e.target===e.currentTarget&&setTrackModal(false)}><div className="w-full max-w-md rounded-2xl border border-border bg-surface p-5 shadow-2xl"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-bold">Create track</h3><p className="text-xs text-text-secondary">Create the track and attach the selected release artists.</p></div><button type="button" onClick={()=>setTrackModal(false)}><X size={16}/></button></div><div className="space-y-4"><Field label="Track title *"><input className="input w-full" autoFocus value={newTrack.title} onChange={e=>setNewTrack({...newTrack,title:e.target.value})}/></Field><Field label="ISRC"><input className="input w-full" value={newTrack.isrc_code} onChange={e=>setNewTrack({...newTrack,isrc_code:e.target.value})}/></Field></div><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>setTrackModal(false)}>Cancel</Button><Button type="button" loading={saving} disabled={saving} onClick={createTrack}>Create Track</Button></div></div></div>}
    <AddContractWizard isOpen={contractModal} onClose={()=>setContractModal(false)} onCreated={attachCreatedContract}/>
  </div>;
}
