/**
 * Platform Event Registry — registered event definitions.
 * Every published event must appear here.
 */

import type { EventDefinition } from "../types";

export const PLATFORM_EVENT_DEFINITIONS: EventDefinition[] = [
  // ── Documents ──────────────────────────────────────────────────────────
  {
    name: "contracts.document.uploaded",
    version: "1.0",
    producer: "contract-center",
    description: "A document was uploaded and linked to a contract",
    payloadSchema: {
      contractId: "number",
      documentId: "string",
      fileName: "string?",
    },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "indefinite",
  },
  {
    name: "contracts.document.deleted",
    version: "1.0",
    producer: "contract-center",
    description: "A contract document was soft-deleted",
    payloadSchema: { contractId: "number", documentId: "string" },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "365d",
  },

  // ── Intelligence / verification ────────────────────────────────────────
  {
    name: "contracts.verification.completed",
    version: "1.0",
    producer: "contract-center",
    description: "Human verification session completed",
    payloadSchema: {
      contractId: "number",
      documentId: "string",
      sessionId: "string?",
    },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "indefinite",
  },
  {
    name: "contracts.verification.reopened",
    version: "1.0",
    producer: "contract-center",
    description: "Verification session reopened",
    payloadSchema: { contractId: "number", documentId: "string" },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "365d",
  },
  {
    name: "contracts.extraction.completed",
    version: "1.0",
    producer: "contract-center",
    description: "Document extraction job completed",
    payloadSchema: {
      contractId: "number?",
      documentId: "string",
      extractionId: "string?",
    },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "90d",
  },

  // ── Verified domain ────────────────────────────────────────────────────
  {
    name: "contracts.verified.created",
    version: "1.0",
    producer: "contract-center",
    description: "Verified contract domain record created",
    payloadSchema: {
      contractId: "number",
      verifiedContractId: "string",
    },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "indefinite",
  },
  {
    name: "contracts.verified.updated",
    version: "1.0",
    producer: "contract-center",
    description: "Verified contract domain updated",
    payloadSchema: {
      contractId: "number",
      verifiedContractId: "string",
    },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "indefinite",
  },
  {
    name: "contracts.verified.reverified",
    version: "1.0",
    producer: "contract-center",
    description: "Contract re-verified from new session",
    payloadSchema: {
      contractId: "number",
      verifiedContractId: "string",
    },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "indefinite",
  },

  // ── Relationships ──────────────────────────────────────────────────────
  {
    name: "contracts.relationship.created",
    version: "1.0",
    producer: "contract-center",
    description: "Contract relationship confirmed",
    payloadSchema: {
      contractId: "number",
      relationshipId: "string",
      targetEntityType: "string?",
    },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "indefinite",
  },
  {
    name: "contracts.relationship.removed",
    version: "1.0",
    producer: "contract-center",
    description: "Contract relationship removed",
    payloadSchema: { contractId: "number", relationshipId: "string" },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "365d",
  },
  {
    name: "contracts.relationship.suggested",
    version: "1.0",
    producer: "contract-center",
    description: "Relationship suggestion created",
    payloadSchema: { contractId: "number", suggestionId: "string" },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "90d",
  },
  {
    name: "contracts.relationship.rejected",
    version: "1.0",
    producer: "contract-center",
    description: "Relationship suggestion rejected",
    payloadSchema: { contractId: "number", suggestionId: "string" },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "90d",
  },

  // ── Lifecycle ──────────────────────────────────────────────────────────
  {
    name: "contracts.lifecycle.status_changed",
    version: "1.0",
    producer: "contract-center",
    description: "Contract lifecycle status changed",
    payloadSchema: { contractId: "number", from: "string", to: "string" },
    consumers: ["notifications", "reminders"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "indefinite",
  },
  {
    name: "contracts.lifecycle.activated",
    version: "1.0",
    producer: "contract-center",
    description: "Contract became active",
    payloadSchema: { contractId: "number" },
    consumers: ["notifications", "reminders"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "indefinite",
  },
  {
    name: "contracts.lifecycle.expired",
    version: "1.0",
    producer: "contract-center",
    description: "Contract expired",
    payloadSchema: { contractId: "number" },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "indefinite",
  },
  {
    name: "contracts.lifecycle.renewal_due",
    version: "1.0",
    producer: "contract-center",
    description: "Contract renewal is due",
    payloadSchema: { contractId: "number" },
    consumers: ["notifications", "reminders"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "indefinite",
  },
  {
    name: "contracts.lifecycle.renewed",
    version: "1.0",
    producer: "contract-center",
    description: "Contract manually marked renewed",
    payloadSchema: { contractId: "number" },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "indefinite",
  },
  {
    name: "contracts.lifecycle.superseded",
    version: "1.0",
    producer: "contract-center",
    description: "Contract superseded by another",
    payloadSchema: {
      contractId: "number",
      supersedesContractId: "number?",
      supersededByContractId: "number?",
    },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "indefinite",
  },
  {
    name: "contracts.lifecycle.amended",
    version: "1.0",
    producer: "contract-center",
    description: "Amendment registered on contract",
    payloadSchema: {
      contractId: "number",
      amendmentId: "string",
      amendmentNumber: "string?",
    },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "indefinite",
  },

  // ── Platform self-events ───────────────────────────────────────────────
  {
    name: "platform.events.replayed",
    version: "1.0",
    producer: "platform",
    description: "An event or DLQ entry was replayed",
    payloadSchema: { originalEventId: "string", replayEventId: "string?" },
    consumers: [],
    idempotencyStrategy: "none",
    retentionPolicy: "90d",
  },
  {
    name: "notifications.created",
    version: "1.0",
    producer: "notifications",
    description: "In-app notification created",
    payloadSchema: {
      notificationId: "string",
      userId: "number",
      type: "string",
    },
    consumers: [],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "90d",
  },
  {
    name: "reminders.created",
    version: "1.0",
    producer: "notifications",
    description: "Reminder scheduled",
    payloadSchema: { reminderId: "string", type: "string", dueAt: "string" },
    consumers: [],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "90d",
  },
  {
    name: "reminders.fired",
    version: "1.0",
    producer: "notifications",
    description: "Reminder fired (in-app only)",
    payloadSchema: { reminderId: "string" },
    consumers: ["notifications"],
    idempotencyStrategy: "event_subscriber",
    retentionPolicy: "90d",
  },
];

/** Map legacy PascalCase / module-local event types → platform names */
export const LEGACY_EVENT_MAP: Record<string, string> = {
  ContractActivated: "contracts.lifecycle.activated",
  ContractExpired: "contracts.lifecycle.expired",
  ContractRenewalDue: "contracts.lifecycle.renewal_due",
  ContractRenewed: "contracts.lifecycle.renewed",
  ContractSuperseded: "contracts.lifecycle.superseded",
  ContractAmended: "contracts.lifecycle.amended",
  LifecycleStatusChanged: "contracts.lifecycle.status_changed",
  RelationshipSuggested: "contracts.relationship.suggested",
  RelationshipCreated: "contracts.relationship.created",
  RelationshipUpdated: "contracts.relationship.created",
  RelationshipRemoved: "contracts.relationship.removed",
  RelationshipRejected: "contracts.relationship.rejected",
  VerifiedContractCreated: "contracts.verified.created",
  VerifiedContractUpdated: "contracts.verified.updated",
  VerifiedContractReverified: "contracts.verified.reverified",
  DocumentUploaded: "contracts.document.uploaded",
  DocumentDeleted: "contracts.document.deleted",
  "extraction.completed": "contracts.extraction.completed",
  "verification.completed": "contracts.verification.completed",
  "verification.reopened": "contracts.verification.reopened",
};
