[pytest]
filterwarnings =
    ignore:Please use `import python_multipart` instead:PendingDeprecationWarning
    ignore:'crypt' is deprecated and slated for removal in Python 3.13:DeprecationWarning
    ignore:PyPDF2 is deprecated:DeprecationWarning
    ignore:on_event is deprecated:DeprecationWarning
