"use client";

import { useEffect, useState } from "react";
import { Check, Loader2, Pencil, RotateCcw, X } from "lucide-react";
import Card from "@/components/ui/Card";
import Badge from "@/components/ui/Badge";
import Button from "@/components/ui/Button";
import api from "@/lib/api";

type Field = { id:string; fieldKey:string; fieldLabel:string; extractedValue:any; workingValue:any; confidence:number; confidenceBand:string; verificationState:string; isRequired:boolean; differsFromAi:boolean };
type Verification = { extractionId:string; documentId:string; contractId:number|null; extractionStatus:string; documentType:string|null; overallConfidence:number|null; isDocumentVerified:boolean; session:any; progress:any; fields:Field[]; promotion?:any };

export default function ContractVerificationWorkspace({ documentId, extractionId }: { documentId:string; extractionId:string }) {
  const [data,setData]=useState<Verification|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState(""),[message,setMessage]=useState("");
  const load=async()=>{try{setError("");const r=await api.get("/ai/contracts/verification",{params:{document_id:documentId,extraction_id:extractionId}});setData(r.data?.data||null)}catch(e:any){setError(e?.response?.data?.message||e?.response?.data?.error||"Unable to load verification workspace.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[documentId,extractionId]);
  const update=async(field:Field,action:"accept"|"reject"|"edit",value?:string)=>{setBusy(field.fieldKey);setError("");try{await api.patch("/ai/contracts/verification",{document_id:documentId,extraction_id:extractionId,field_key:field.fieldKey,action,value});await load()}catch(e:any){setError(e?.response?.data?.message||"Unable to update field.")}finally{setBusy(null)}};
  const complete=async()=>{setBusy("complete");setError("");setMessage("");try{const r=await api.post("/ai/contracts/verification",{document_id:documentId,extraction_id:extractionId,action:"complete"});setData(r.data?.data||null);setMessage(r.data?.data?.promotion?.version?`Verification complete. Contract version ${r.data.data.promotion.version} is now current.`:"Verification completed. Promotion will be retried if necessary.")}catch(e:any){setError(e?.response?.data?.message||"Unable to complete verification.")}finally{setBusy(null)}};
  if(loading)return <div className="py-12 flex items-center justify-center gap-2 text-text-secondary"><Loader2 className="animate-spin" size={18}/> Loading verification workspace…</div>;
  if(!data)return <div className="rounded-xl border border-danger/30 bg-danger/10 p-4 text-sm text-danger">{error||"Verification data unavailable."}</div>;
  const progress=data.progress;
  return <div className="space-y-5">{error&&<div className="rounded-xl border border-danger/30 bg-danger/10 p-3 text-sm text-danger">{error}</div>}{message&&<div className="rounded-xl border border-success/30 bg-success/10 p-3 text-sm text-success">{message}</div>}
    <Card title="Human verification"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-white">Review extracted contract data before it becomes authoritative.</p><p className="text-xs text-text-secondary mt-1">AI extraction remains a draft. Every field must be reviewed.</p></div><div className="flex items-center gap-2"><Badge variant={progress.canComplete?"success":"warn"} size="sm">{progress.reviewed}/{progress.total} reviewed</Badge>{data.session&&<Badge variant="default" size="sm">Session v{data.session.version}</Badge>}</div></div><div className="mt-4 h-2 rounded-full bg-white/10 overflow-hidden"><div className="h-full bg-current transition-all" style={{width:`${progress.percent}%`}}/></div></Card>
    <Card title="Extracted fields"><div className="space-y-3">{data.fields.map(f=><div key={f.id} className="rounded-xl border border-white/10 bg-white/[0.02] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="text-sm font-medium text-white">{f.fieldLabel}</span>{f.isRequired&&<Badge variant="warn" size="sm">Required</Badge>}</div><p className="text-xs text-text-secondary mt-1">{f.fieldKey} · {Math.round(f.confidence)}% confidence · {f.confidenceBand}</p></div><Badge variant={f.verificationState==="draft"?"warn":f.verificationState==="rejected"?"danger":"success"} size="sm">{f.verificationState}</Badge></div><div className="mt-3 grid gap-2 md:grid-cols-2"><div className="rounded-lg bg-white/5 p-3"><p className="text-[11px] uppercase tracking-wide text-text-secondary">AI extraction</p><p className="text-sm text-white mt-1 whitespace-pre-wrap break-words">{String(f.extractedValue??"—")}</p></div><div className="rounded-lg bg-white/5 p-3"><p className="text-[11px] uppercase tracking-wide text-text-secondary">Working value</p><p className="text-sm text-white mt-1 whitespace-pre-wrap break-words">{String(f.workingValue??"—")}</p></div></div><div className="mt-3 flex flex-wrap gap-2"><Button variant="secondary" size="sm" disabled={!!busy} onClick={()=>void update(f,"accept")}><Check size={13}/> Accept</Button><Button variant="secondary" size="sm" disabled={!!busy} onClick={()=>{const value=window.prompt(`Edit ${f.fieldLabel}`,String(f.workingValue??""));if(value!==null)void update(f,"edit",value)}}><Pencil size={13}/> Edit & accept</Button><Button variant="secondary" size="sm" disabled={!!busy} onClick={()=>void update(f,"reject")}><X size={13}/> Reject</Button>{busy===f.fieldKey&&<Loader2 size={15} className="animate-spin"/>}</div></div>)}</div></Card>
    <Card title="Verification decision"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-white">{progress.canComplete?"All fields have been reviewed.":`${progress.draft} field(s) still require review.`}</p><p className="text-xs text-text-secondary mt-1">Completion writes the verified layer and invokes the existing immutable contract-version promotion.</p></div><Button variant="primary" size="sm" disabled={!progress.canComplete||busy=== "complete"||data.isDocumentVerified} onClick={()=>void complete()}>{busy==="complete"?<Loader2 size={14} className="animate-spin"/>:<Check size={14}/>} {data.isDocumentVerified?"Verified":"Complete verification"}</Button></div></Card>
    {data.isDocumentVerified&&<Card title="Promotion result"><p className="text-sm text-white">Verified contract created.</p><p className="text-xs text-text-secondary mt-1">{data.promotion?.verifiedContractId?`Verified contract ID: ${data.promotion.verifiedContractId}`:"The verification record is complete; check version history for the promoted version."}</p></Card>}
  </div>;
}
