/** R4–R7 residual authorization regression gate. */
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { requireLegacyIntOrgId, requirePositiveIntId, ResourceAuthError, resourceAuthErrorResponse, trackOrgScopeWhere } from "../resource-authorization";
import type { OrganizationContext } from "../organization-context";
const ORG_A = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"; const ORG_B = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb";
function ctx(org: "A" | "B", legacyIntOrgId = org === "A" ? 10 : 20): OrganizationContext { const organizationId = org === "A" ? ORG_A : ORG_B; return { organizationId, organization: null, tenantId: organizationId, membership: null, role: "owner", permissions: [], isSuperAdmin: false, userId: org === "A" ? 10 : 20, userEmail: `${org.toLowerCase()}@example.com`, legacyIntOrgId, dataScopeSource: "membership" }; }
let passed = 0; let failed = 0;
async function test(name: string, fn: () => void | Promise<void>) { try { await fn(); passed++; console.log(`  ✓ ${name}`); } catch (e: any) { failed++; console.error(`  ✗ ${name}`); console.error(`    ${e?.message || e}`); } }
function assertFailClosed(fn: () => unknown) { assert.throws(fn, (err: unknown) => err instanceof ResourceAuthError && (err.status === 400 || err.status === 403)); }
await test("R4-1: role-name availability is org-bound", async () => { const source = await readFile("app/api/iam/roles/route.ts", "utf8"); assert.match(source, /where:\s*\{\s*name:\s*body\.name,\s*organization_id\s*\}/s); assert.doesNotMatch(source, /roles\.findUnique\(\{\s*where:\s*\{\s*name:/s); });
await test("R4-2: role uniqueness conflicts are generic", async () => { const source = await readFile("app/api/iam/roles/route.ts", "utf8"); assert.match(source, /err\?\.code\s*===\s*[\"']P2002[\"']/); assert.match(source, /Role name unavailable/); });
await test("R4-3: ordinary users cannot select an arbitrary organization", async () => { const source = await readFile("app/api/iam/roles/route.ts", "utf8"); assert.match(source, /platform && body\.organization_id/); assert.match(source, /:\s*\(user as any\)\.organization_id/); });
await test("R4-4: system roles remain protected", async () => { const source = await readFile("app/api/iam/roles/route.ts", "utf8"); assert.match(source, /Cannot modify system role/); assert.match(source, /Cannot delete system role/); });
await test("R5-1: AI contract resolution uses strict ownership validation", async () => { const source = await readFile("app/api/ai/contracts/route.ts", "utf8"); assert.match(source, /requireAIEntityInOrg/); assert.match(source, /requireAIEntityInOrg\(entityType, link\.entity_id, ctx\)/); });
await test("R5-2: core-write validates contract/release/document ownership", async () => { const source = await readFile("app/api/ai/core-write/route.ts", "utf8"); assert.match(source, /requireAIEntityInOrg\("contract", contractId, ctx\)/); assert.match(source, /requireAIEntityInOrg\("release", releaseId, ctx\)/); assert.match(source, /requireAIEntityInOrg\("ai_contract_document", contractDocumentId, ctx\)/); });
await test("R5-3: release integration validates plan references", async () => { const source = await readFile("app/api/ai/release-integration/route.ts", "utf8"); assert.match(source, /requireReleaseInOrg\(releaseId, ctx\)/); assert.match(source, /requireContractInOrg\(contractIdForRun, ctx\)/); });
await test("R5-4: release integration validates every attach reference", async () => { const source = await readFile("app/api/ai/release-integration/route.ts", "utf8"); assert.match(source, /requireAIEntityInOrg\(link\?\.entity_type, link\?\.entity_id, ctx\)/); });
await test("R5-5: strict AI helper rejects unsupported types", async () => { const source = await readFile("lib/auth/ai-entity-authorization.ts", "utf8"); assert.match(source, /Unsupported entity_type/); assert.match(source, /default:/); });
await test("R5-6: strict AI helper uses canonical resource guards", async () => { const source = await readFile("lib/auth/ai-entity-authorization.ts", "utf8"); assert.match(source, /requireContractInOrg/); assert.match(source, /requireReleaseInOrg/); assert.match(source, /requireAIContractDocumentInOrg/); });
await test("R6-1: legacy organization conversion rejects invalid scope", () => { assert.equal(requireLegacyIntOrgId(ctx("A")), 10); assertFailClosed(() => requireLegacyIntOrgId(ctx("A", 0))); assertFailClosed(() => requireLegacyIntOrgId(ctx("A", Number.NaN))); });
await test("R6-2: positive-id conversion never invents 0 or 1", () => { assert.equal(requirePositiveIntId("42"), 42); assertFailClosed(() => requirePositiveIntId("")); assertFailClosed(() => requirePositiveIntId("0")); assertFailClosed(() => requirePositiveIntId("abc")); });
await test("R6-3: search uses strict legacy integer scope", async () => { const source = await readFile("app/api/search/route.ts", "utf8"); assert.match(source, /requireLegacyIntOrgId/); assert.doesNotMatch(source, /parseInt\(orgId\)\s*\|\|\s*0/); });
await test("R6-4: reports no longer coerce UUID organizations", async () => { const source = await readFile("lib/reports.ts", "utf8"); assert.match(source, /function orgFilter\(orgId: string\)/); assert.doesNotMatch(source, /Number\(orgId\)\s*\|\|\s*orgId/); assert.match(source, /requireLegacyIntOrgId\(ctx\)/); });
await test("R6-5: AI audit no longer coerces UUID organizations", async () => { const source = await readFile("lib/ai-audit.ts", "utf8"); assert.match(source, /function orgFilter\(orgId: string\)/); assert.doesNotMatch(source, /Number\(orgId\)\s*\|\|\s*orgId/); assert.match(source, /requireLegacyIntOrgId\(ctx\)/); });
await test("R6-6: track scope remains organization-derived", () => { const serialized = JSON.stringify(trackOrgScopeWhere(ctx("A"))); assert.match(serialized, new RegExp(ORG_A)); assert.doesNotMatch(serialized, new RegExp(ORG_B)); });
await test("R7-1: remediation scope contains source/test files only", async () => { for (const file of ["app/api/iam/roles/route.ts", "app/api/ai/contracts/route.ts", "app/api/ai/core-write/route.ts", "app/api/ai/release-integration/route.ts", "app/api/search/route.ts", "lib/reports.ts", "lib/ai-audit.ts"]) assert.ok(file.endsWith(".ts")); });
await test("R7-2: authorization errors remain structured", () => { const response = resourceAuthErrorResponse(new ResourceAuthError("Denied", 403, "PLATFORM_AUTHORITY_REQUIRED")); assert.equal(response.status, 403); assert.equal(response.body.code, "PLATFORM_AUTHORITY_REQUIRED"); });
console.log(`\nR4-R7 HTTP boundary tests: ${passed} passed, ${failed} failed`); if (failed > 0) process.exitCode = 1;
