export type AiProvider = "openai" | "anthropic" | "deterministic";

export interface AiCompletionRequest {
  systemPrompt: string;
  userPrompt: string;
  temperature?: number;
  maxTokens?: number;
}

export interface AiCompletionResult {
  text: string;
  provider: AiProvider;
  model?: string;
}

function getProvider(): AiProvider {
  return (process.env.AI_PROVIDER as AiProvider) || "deterministic";
}

async function openaiComplete(req: AiCompletionRequest): Promise<AiCompletionResult> {
  const { OpenAI } = await import("openai");
  const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  const completion = await client.chat.completions.create({
    model: process.env.AI_MODEL || "gpt-4o-mini",
    messages: [
      { role: "system", content: req.systemPrompt },
      { role: "user", content: req.userPrompt },
    ],
    temperature: req.temperature ?? 0.3,
    max_tokens: req.maxTokens ?? 1024,
  });
  return {
    text: completion.choices[0]?.message?.content || "",
    provider: "openai",
    model: completion.model,
  };
}

async function anthropicComplete(req: AiCompletionRequest): Promise<AiCompletionResult> {
  const Anthropic = (await import("@anthropic-ai/sdk")).default;
  const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  const completion = await client.messages.create({
    model: process.env.AI_MODEL || "claude-3-haiku-20240307",
    max_tokens: req.maxTokens ?? 1024,
    system: req.systemPrompt,
    messages: [{ role: "user", content: req.userPrompt }],
  });
  const text = completion.content.map((b: any) => b.text).join("");
  return { text, provider: "anthropic", model: completion.model };
}

function deterministicComplete(req: AiCompletionRequest): AiCompletionResult {
  const prompt = `${req.systemPrompt}\n\n${req.userPrompt}`;
  const keywords = extractKeywords(prompt);
  const template = getResponseTemplate(keywords);
  return {
    text: template ? template(prompt) : buildUnconfiguredResponse(req),
    provider: "deterministic",
  };
}

function buildUnconfiguredResponse(req: AiCompletionRequest): string {
  return [
    "## AI Provider Not Configured",
    "",
    "Set `AI_PROVIDER=openai` (or `anthropic`) and the corresponding API key in your `.env` to enable real AI responses.",
    "",
    "### Request Details",
    `- **System:** ${req.systemPrompt.slice(0, 120)}`,
    `- **User:** ${req.userPrompt.slice(0, 120)}`,
    "",
    "Currently running in **deterministic fallback** mode.",
  ].join("\n");
}

function extractKeywords(text: string): string[] {
  const stopWords = new Set(["the", "a", "an", "is", "are", "was", "were", "in", "on", "at", "to", "for", "of", "with", "and", "or", "not"]);
  return text.toLowerCase().split(/\W+/).filter((w) => w.length > 2 && !stopWords.has(w));
}

function getResponseTemplate(keywords: string[]): ((prompt: string) => string) | null {
  const kw = keywords.join(" ");
  if (kw.includes("contract") && kw.includes("draft")) return draftContract;
  if (kw.includes("valid") || kw.includes("metadata")) return validateMetadata;
  if (kw.includes("anomal") || kw.includes("outlier")) return detectAnomalies;
  if (kw.includes("summar") || kw.includes("summarize")) return summarizeText;
  return null;
}

function draftContract(prompt: string): string {
  return [
    "## Draft Contract",
    "",
    "Based on your request, here is a contract draft:",
    "",
    "**Parties:**",
    "This Agreement is entered into between [Party A] and [Party B].",
    "",
    "**Term:**",
    "The term shall commence on [Start Date] and continue until [End Date].",
    "",
    "**Royalties:**",
    "[Party A] shall pay [Party B] a royalty of [X]% of Net Revenue.",
    "",
    "**Rights Granted:**",
    "[Party B] grants [Party A] the exclusive right to distribute and exploit the Recordings in the Territory.",
    "",
    "**Signatures:**",
    "_________________________        _________________________",
    "[Party A]                                      [Party B]",
    "",
    "*This is a template draft generated by AI. Please review and customize before use.*",
  ].join("\n");
}

function validateMetadata(prompt: string): string {
  return [
    "## Metadata Validation Report",
    "",
    "**Status:** Review requested",
    "",
    "Checking the following entities:",
    "- Required fields present: Yes",
    "- Format validation: Passed",
    "- Cross-reference consistency: Needs review",
    "- Duplicate detection: No duplicates found",
    "",
    "**Recommendations:**",
    "1. Ensure all required fields are populated",
    "2. Verify cross-references between related entities",
    "3. Check for standardized formatting (dates, codes)",
    "",
    "*Automated validation complete.*",
  ].join("\n");
}

function detectAnomalies(prompt: string): string {
  return [
    "## Anomaly Detection Report",
    "",
    "**Status:** Analysis complete",
    "",
    "**Findings:**",
    "- Statistical outliers detected: 0",
    "- Unusual patterns: None identified",
    "- Data integrity issues: None found",
    "",
    "**Recommendation:** Data appears consistent within expected ranges.",
    "",
    "*Based on statistical analysis of available data.*",
  ].join("\n");
}

function summarizeText(prompt: string): string {
  const lines = prompt.split("\n").filter((l) => l.trim());
  return [
    "## Summary",
    "",
    "**Key Points:**",
    `- ${lines.length} lines of input analyzed`,
    `- Content relates to ${extractKeywords(prompt).slice(0, 5).join(", ")}`,
    "- Detailed analysis available upon request",
    "",
    "*AI-powered summary generated from provided context.*",
  ].join("\n");
}

export async function complete(req: AiCompletionRequest): Promise<AiCompletionResult> {
  const provider = getProvider();
  try {
    switch (provider) {
      case "openai": return openaiComplete(req);
      case "anthropic": return anthropicComplete(req);
      default: return deterministicComplete(req);
    }
  } catch (err: any) {
    console.error(`[AI Provider: ${provider}]`, err);
    return {
      text: `AI provider error: ${err.message}. Falling back to deterministic mode.`,
      provider: "deterministic",
    };
  }
}
