"""fix_final_schema_discrepancies

Revision ID: 05e48294ecdc
Revises: 815fda7f11d3
Create Date: 2026-02-10 12:11:03.356638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05e48294ecdc'
down_revision: Union[str, None] = '815fda7f11d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    is_pg = bind.dialect.name == 'postgresql'
    print(f"DEBUG: Dialect name is '{bind.dialect.name}', is_pg={is_pg}")
    bool_false = 'false' if is_pg else '0'

    def safe_drop_index(batch_op, index_name):
        indexes = inspector.get_indexes(batch_op.impl.table_name)
        if any(idx['name'] == index_name for idx in indexes):
            batch_op.drop_index(index_name)
        else:
            print(f"Index {index_name} not found on {batch_op.impl.table_name}, skipping drop.")

    def safe_create_index(batch_op, index_name, columns, **kw):
        indexes = inspector.get_indexes(batch_op.impl.table_name)
        if not any(idx['name'] == index_name for idx in indexes):
            batch_op.create_index(index_name, columns, **kw)
        else:
            print(f"Index {index_name} already exists on {batch_op.impl.table_name}, skipping creation.")

    def safe_add_column(batch_op, column):
        table_name = batch_op.impl.table_name
        columns = [c['name'] for c in inspector.get_columns(table_name)]
        if column.name not in columns:
            batch_op.add_column(column)
        else:
            print(f"Column {column.name} already exists on {table_name}, skipping addition.")

    def safe_create_fk(batch_op, constraint_name, referent_table, local_cols, remote_cols, **kwargs):
        table_name = batch_op.impl.table_name
        fks = inspector.get_foreign_keys(table_name)
        if not any(fk.get('name') == constraint_name for fk in fks):
            batch_op.create_foreign_key(constraint_name, referent_table, local_cols, remote_cols, **kwargs)
        else:
            print(f"FK {constraint_name} already exists on {table_name}, skipping.")

    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('distributors', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_distributors_id'))
    #     batch_op.drop_index(batch_op.f('ix_distributors_name'))

    # op.drop_table('distributors')
    # Moved to end
    # op.execute('DROP TABLE IF EXISTS distributors')
    # with op.batch_alter_table('contacts', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_contacts_email'))
    #     batch_op.drop_index(batch_op.f('ix_contacts_id'))

    # op.drop_table('contacts')
    # Moved to end
    # op.execute('DROP TABLE IF EXISTS contacts')
    # with op.batch_alter_table('companies', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_companies_id'))
    #     batch_op.drop_index(batch_op.f('ix_companies_name'))
    #     batch_op.drop_index(batch_op.f('ix_companies_type'))

    # op.drop_table('companies')
    # Moved to end
    # op.execute('DROP TABLE IF EXISTS companies')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        # safe_add_column(batch_op, sa.Column('organization_id', sa.Integer(), server_default='1', nullable=False))
        # safe_add_column(batch_op, sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        # batch_op.create_index(batch_op.f('ix_artists_organization_id'), ['organization_id'], unique=False)
        pass

    with op.batch_alter_table('contract_assets', schema=None) as batch_op:
        safe_drop_index(batch_op, batch_op.f('ix_contract_assets_v1_org_contract'))
        safe_drop_index(batch_op, batch_op.f('ix_contract_assets_v1_organization_id'))
        # batch_op.drop_index(batch_op.f('ix_contract_assets_v1_org_contract'))
        # batch_op.drop_index(batch_op.f('ix_contract_assets_v1_organization_id'))
        safe_create_index(batch_op, 'ix_contract_assets_org_contract', ['organization_id', 'contract_id'], unique=False)

    with op.batch_alter_table('contract_documents', schema=None) as batch_op:
        safe_drop_index(batch_op, batch_op.f('ix_contract_documents_v1_org_contract'))
        safe_drop_index(batch_op, batch_op.f('ix_contract_documents_v1_organization_id'))
        safe_drop_index(batch_op, batch_op.f('ix_contract_documents_v1_unique_version'))
        # batch_op.drop_index(batch_op.f('ix_contract_documents_v1_org_contract'))
        # batch_op.drop_index(batch_op.f('ix_contract_documents_v1_organization_id'))
        # batch_op.drop_index(batch_op.f('ix_contract_documents_v1_unique_version'))
        safe_create_index(batch_op, 'ix_contract_documents_org_contract', ['organization_id', 'contract_id'], unique=False)
        safe_create_index(batch_op, 'ix_contract_documents_unique_version', ['contract_id', 'version'], unique=True)

    with op.batch_alter_table('contract_parties', schema=None) as batch_op:
        # batch_op.alter_column('split_percent',
        #        existing_type=sa.NUMERIC(precision=5, scale=2),
        #        type_=sa.Numeric(precision=6, scale=3),
        #        existing_nullable=True)
        safe_drop_index(batch_op, batch_op.f('ix_contract_parties_v1_org_contract'))
        safe_drop_index(batch_op, batch_op.f('ix_contract_parties_v1_organization_id'))
        # batch_op.drop_index(batch_op.f('ix_contract_parties_v1_org_contract'))
        # batch_op.drop_index(batch_op.f('ix_contract_parties_v1_organization_id'))
        safe_create_index(batch_op, 'ix_contract_parties_org_contract', ['organization_id', 'contract_id'], unique=False)

    def safe_drop_column(batch_op, col_name):
        table_name = batch_op.impl.table_name
        col_names = [c['name'] for c in inspector.get_columns(table_name)]
        if col_name in col_names:
            batch_op.drop_column(col_name)
        else:
            print(f"Column {col_name} does not exist on {table_name}, skipping drop.")

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        safe_add_column(batch_op, sa.Column('type', sa.String(length=50), nullable=True))
        safe_add_column(batch_op, sa.Column('status_quo_override', sa.String(length=50), nullable=True))
        safe_drop_index(batch_op, batch_op.f('ix_contracts_v1_created_by'))
        safe_drop_index(batch_op, batch_op.f('ix_contracts_v1_org_number'))
        safe_drop_index(batch_op, batch_op.f('ix_contracts_v1_organization_id'))
        safe_create_index(batch_op, 'ix_contracts_org_number', ['organization_id', 'contract_number'], unique=True)
        safe_create_index(batch_op, 'ix_contracts_organization_id', ['organization_id'], unique=False)
        safe_drop_column(batch_op, 'contract_type')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        safe_add_column(batch_op, sa.Column('organization_id', sa.Integer(), server_default='1', nullable=False))
        safe_add_column(batch_op, sa.Column('checksum', sa.String(length=64), nullable=True))
        safe_add_column(batch_op, sa.Column('is_deleted', sa.Boolean(), server_default=sa.text(bool_false), nullable=False))
        safe_create_index(batch_op, batch_op.f('ix_documents_organization_id'), ['organization_id'], unique=False)


    with op.batch_alter_table('events', schema=None) as batch_op:
        safe_add_column(batch_op, sa.Column('organization_id', sa.Integer(), server_default='1', nullable=False))
        safe_add_column(batch_op, sa.Column('event_type', sa.String(length=100), server_default='general', nullable=False))
        safe_add_column(batch_op, sa.Column('status', sa.String(length=50), server_default='scheduled', nullable=False))
        safe_add_column(batch_op, sa.Column('is_deleted', sa.Boolean(), server_default=sa.text(bool_false), nullable=False))
        safe_create_index(batch_op, batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        safe_create_index(batch_op, batch_op.f('ix_events_organization_id'), ['organization_id'], unique=False)
        safe_create_index(batch_op, batch_op.f('ix_events_status'), ['status'], unique=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        safe_add_column(batch_op, sa.Column('organization_id', sa.Integer(), server_default='1', nullable=False))
        safe_add_column(batch_op, sa.Column('is_deleted', sa.Boolean(), server_default=sa.text(bool_false), nullable=False))
        safe_create_index(batch_op, batch_op.f('ix_notes_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('releases', schema=None) as batch_op:
        safe_add_column(batch_op, sa.Column('organization_id', sa.Integer(), server_default='1', nullable=False))
        safe_add_column(batch_op, sa.Column('is_deleted', sa.Boolean(), server_default=sa.text(bool_false), nullable=False))
        safe_create_index(batch_op, batch_op.f('ix_releases_organization_id'), ['organization_id'], unique=False)
        # batch_op.drop_constraint(None, type_='foreignkey')
        safe_create_fk(batch_op, batch_op.f('fk_releases_distributor_id_organizations'), 'organizations', ['distributor_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        safe_add_column(batch_op, sa.Column('organization_id', sa.Integer(), server_default='1', nullable=False))
        safe_add_column(batch_op, sa.Column('assigned_to_user_id', sa.Integer(), nullable=True))
        safe_add_column(batch_op, sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        safe_add_column(batch_op, sa.Column('linked_entity_type', sa.String(length=50), nullable=True))
        safe_add_column(batch_op, sa.Column('linked_entity_id', sa.Integer(), nullable=True))
        safe_add_column(batch_op, sa.Column('source_type', sa.String(length=50), server_default='manual', nullable=False))
        safe_add_column(batch_op, sa.Column('source_id', sa.Integer(), server_default=sa.text('0'), nullable=False))
        safe_add_column(batch_op, sa.Column('is_deleted', sa.Boolean(), server_default=sa.text(bool_false), nullable=False))
        safe_create_index(batch_op, batch_op.f('ix_tasks_organization_id'), ['organization_id'], unique=False)
        safe_create_index(batch_op, batch_op.f('ix_tasks_source_id'), ['source_id'], unique=False)
        safe_create_index(batch_op, batch_op.f('ix_tasks_source_type'), ['source_type'], unique=False)
        existing_uq = [uc['name'] for uc in inspector.get_unique_constraints('tasks')]
        if 'uq_task_org_source' not in existing_uq:
            batch_op.create_unique_constraint('uq_task_org_source', ['organization_id', 'source_type', 'source_id'])
        # batch_op.drop_constraint(None, type_='foreignkey')
        safe_create_fk(batch_op, batch_op.f('fk_tasks_created_by_user_id_users'), 'users', ['created_by_user_id'], ['id'])
        safe_create_fk(batch_op, batch_op.f('fk_tasks_assigned_to_user_id_users'), 'users', ['assigned_to_user_id'], ['id'])
        safe_drop_column(batch_op, 'assigned_to_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        safe_add_column(batch_op, sa.Column('organization_id', sa.Integer(), server_default='1', nullable=False))
        safe_create_index(batch_op, batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('works', schema=None) as batch_op:
        safe_add_column(batch_op, sa.Column('organization_id', sa.Integer(), server_default='1', nullable=False))
        safe_add_column(batch_op, sa.Column('is_deleted', sa.Boolean(), server_default=sa.text(bool_false), nullable=False))
        safe_create_index(batch_op, batch_op.f('ix_works_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_works_organization_id'))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        safe_add_column(batch_op, sa.Column('assigned_to_id', sa.INTEGER(), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_assigned_to_id_users'), 'users', ['assigned_to_id'], ['id'])
        batch_op.drop_constraint('uq_task_org_source', type_='unique')
        batch_op.drop_index(batch_op.f('ix_tasks_source_type'))
        batch_op.drop_index(batch_op.f('ix_tasks_source_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_organization_id'))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('source_id')
        batch_op.drop_column('source_type')
        batch_op.drop_column('linked_entity_id')
        batch_op.drop_column('linked_entity_type')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('assigned_to_user_id')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('releases', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['distributor_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_releases_organization_id'))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_organization_id'))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('status')
        batch_op.drop_column('event_type')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_organization_id'))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('checksum')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        safe_add_column(batch_op, sa.Column('contract_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_index('ix_contracts_organization_id')
        batch_op.drop_index('ix_contracts_org_number')
        batch_op.create_index(batch_op.f('ix_contracts_v1_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_v1_org_number'), ['organization_id', 'contract_number'], unique=1)
        batch_op.create_index(batch_op.f('ix_contracts_v1_created_by'), ['created_by'], unique=False)
        batch_op.drop_column('status_quo_override')
        batch_op.drop_column('type')

    with op.batch_alter_table('contract_parties', schema=None) as batch_op:
        batch_op.drop_index('ix_contract_parties_org_contract')
        batch_op.create_index(batch_op.f('ix_contract_parties_v1_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_parties_v1_org_contract'), ['organization_id', 'contract_id'], unique=False)
        batch_op.alter_column('split_percent',
               existing_type=sa.Numeric(precision=6, scale=3),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('contract_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_contract_documents_unique_version')
        batch_op.drop_index('ix_contract_documents_org_contract')
        batch_op.create_index(batch_op.f('ix_contract_documents_v1_unique_version'), ['contract_id', 'version'], unique=1)
        batch_op.create_index(batch_op.f('ix_contract_documents_v1_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_documents_v1_org_contract'), ['organization_id', 'contract_id'], unique=False)

    with op.batch_alter_table('contract_assets', schema=None) as batch_op:
        batch_op.drop_index('ix_contract_assets_org_contract')
        batch_op.create_index(batch_op.f('ix_contract_assets_v1_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_assets_v1_org_contract'), ['organization_id', 'contract_id'], unique=False)

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artists_organization_id'))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('organization_id')

    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('role', sa.VARCHAR(length=100), nullable=True),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)

    op.create_table('distributors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributors_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributors_id'), ['id'], unique=False)

    # ### end Alembic commands ###
