"""add_org_scoping_to_notes

Revision ID: 2236b5c5c373
Revises: 6aa6378bf91b
Create Date: 2026-02-03 23:20:07.176548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2236b5c5c373'
down_revision: Union[str, None] = '6aa6378bf91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Uuid(), nullable=False, server_default='00000000000000000000000000000001'))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_notes_organization_id'), ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_organization_id'))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('organization_id')
    # ### end Alembic commands ###
