"""Add organization_id to documents

Revision ID: 2ed402f88c2f
Revises: 78c67c2ef17c
Create Date: 2026-02-03 19:43:59.871994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed402f88c2f'
down_revision: Union[str, None] = '78c67c2ef17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    with op.batch_alter_table('contract_assets', schema=None) as batch_op:
        batch_op.drop_index('ix_contract_assets_organization_id')

    with op.batch_alter_table('contract_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_contract_documents_organization_id')

    with op.batch_alter_table('contract_parties', schema=None) as batch_op:
        batch_op.drop_index('ix_contract_parties_organization_id')

    with op.batch_alter_table('contract_split_groups', schema=None) as batch_op:
        batch_op.drop_index('ix_contract_split_groups_organization_id')

    with op.batch_alter_table('contract_splits', schema=None) as batch_op:
        batch_op.drop_index('ix_contract_splits_organization_id')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'contract_split_groups', ['group_id'], ['id'])
        batch_op.create_foreign_key(None, 'contract_parties', ['party_id'], ['id'])

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index('ix_contracts_created_by')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('checksum', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_documents_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.drop_index('ix_contacts_email')
        batch_op.drop_index('ix_contacts_id')
        batch_op.create_index(batch_op.f('ix_individuals_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_individuals_id'), ['id'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index('ix_companies_id')
        batch_op.drop_index('ix_companies_name')
        batch_op.drop_index('ix_companies_type')
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_org_type'), ['org_type'], unique=False)

    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('works_admin', schema=None) as batch_op:
        batch_op.drop_index('ix_works_admin_created_by')
        batch_op.drop_index('ix_works_admin_organization_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works_admin', schema=None) as batch_op:
        batch_op.create_index('ix_works_admin_organization_id', ['organization_id'], unique=False)
        batch_op.create_index('ix_works_admin_created_by', ['created_by'], unique=False)

    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'companies', ['distributor_id'], ['id'])

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_org_type'))
        batch_op.drop_index(batch_op.f('ix_organizations_name'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))
        batch_op.create_index('ix_companies_type', ['org_type'], unique=False)
        batch_op.create_index('ix_companies_name', ['name'], unique=False)
        batch_op.create_index('ix_companies_id', ['id'], unique=False)

    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_individuals_id'))
        batch_op.drop_index(batch_op.f('ix_individuals_email'))
        batch_op.create_index('ix_contacts_id', ['id'], unique=False)
        batch_op.create_index('ix_contacts_email', ['email'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_organization_id'))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('checksum')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index('ix_contracts_created_by', ['created_by'], unique=False)

    with op.batch_alter_table('contract_splits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'contract_parties', ['party_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'contract_split_groups', ['group_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('ix_contract_splits_organization_id', ['organization_id'], unique=False)

    with op.batch_alter_table('contract_split_groups', schema=None) as batch_op:
        batch_op.create_index('ix_contract_split_groups_organization_id', ['organization_id'], unique=False)

    with op.batch_alter_table('contract_parties', schema=None) as batch_op:
        batch_op.create_index('ix_contract_parties_organization_id', ['organization_id'], unique=False)

    with op.batch_alter_table('contract_documents', schema=None) as batch_op:
        batch_op.create_index('ix_contract_documents_organization_id', ['organization_id'], unique=False)

    with op.batch_alter_table('contract_assets', schema=None) as batch_op:
        batch_op.create_index('ix_contract_assets_organization_id', ['organization_id'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
