"""add_office_fields_to_tasks

Revision ID: 3482fdf79843
Revises: 3c7c2a1b9f12
Create Date: 2026-02-03 21:36:30.874243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3482fdf79843'
down_revision: Union[str, None] = '3c7c2a1b9f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'organization_id',
                sa.Uuid(),
                nullable=False,
                server_default=sa.text("'00000000-0000-0000-0000-000000000001'"),
            )
        )
        batch_op.add_column(sa.Column('assigned_to_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                'created_by_user_id',
                sa.Integer(),
                nullable=False,
                server_default=sa.text("1"),
            )
        )
        batch_op.add_column(sa.Column('linked_entity_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('linked_entity_id', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                'is_deleted',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0"),
            )
        )
        batch_op.create_index(batch_op.f('ix_tasks_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key('fk_tasks_created_by_user_id', 'users', ['created_by_user_id'], ['id'])
        batch_op.create_foreign_key('fk_tasks_assigned_to_user_id', 'users', ['assigned_to_user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'organization_id',
                sa.Uuid(),
                nullable=False,
                server_default=sa.text("'00000000-0000-0000-0000-000000000001'"),
            )
        )
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_assigned_to_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_tasks_created_by_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_organization_id'))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('linked_entity_id')
        batch_op.drop_column('linked_entity_type')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('assigned_to_user_id')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
