"""add_status_quo_and_task_source

Revision ID: 4053a2735f7d
Revises: 44735e1b0d2b
Create Date: 2026-02-03 23:37:32.560540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4053a2735f7d'
down_revision: Union[str, None] = '44735e1b0d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_quo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_quo_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_quo_items_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_quo_items_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_quo_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_quo_items_issue_type'), ['issue_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_quo_items_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_source_type'), ['source_type'], unique=False)
        batch_op.create_unique_constraint('uq_task_org_source', ['organization_id', 'source_type', 'source_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_task_org_source', type_='unique')
        batch_op.drop_index(batch_op.f('ix_tasks_source_type'))
        batch_op.drop_index(batch_op.f('ix_tasks_source_id'))
        batch_op.drop_column('source_id')
        batch_op.drop_column('source_type')

    with op.batch_alter_table('status_quo_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_quo_items_organization_id'))
        batch_op.drop_index(batch_op.f('ix_status_quo_items_issue_type'))
        batch_op.drop_index(batch_op.f('ix_status_quo_items_id'))
        batch_op.drop_index(batch_op.f('ix_status_quo_items_entity_type'))
        batch_op.drop_index(batch_op.f('ix_status_quo_items_entity_id'))

    op.drop_table('status_quo_items')
    # ### end Alembic commands ###
