"""Fix Contract User ID and Audit Log

Revision ID: 406935f9448d
Revises: 7e0f57e495a3
Create Date: 2026-02-02 10:20:05.416276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406935f9448d'
down_revision: Union[str, None] = '7e0f57e495a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    if 'audit_logs' in inspector.get_table_names():
        columns = [c['name'] for c in inspector.get_columns('audit_logs')]
        indices = [i['name'] for i in inspector.get_indexes('audit_logs')]
        with op.batch_alter_table('audit_logs', schema=None) as batch_op:
            if 'entity_uuid' not in columns:
                batch_op.add_column(sa.Column('entity_uuid', sa.Uuid(), nullable=True))
            if 'ix_audit_logs_entity_uuid' not in indices:
                batch_op.create_index(batch_op.f('ix_audit_logs_entity_uuid'), ['entity_uuid'], unique=False)

    if 'contracts_v1' in inspector.get_table_names():
        columns = [c['name'] for c in inspector.get_columns('contracts_v1')]
        indices = [i['name'] for i in inspector.get_indexes('contracts_v1')]
        with op.batch_alter_table('contracts_v1', schema=None) as batch_op:
            # We need to drop created_by (which was UUID) and recreate it as Integer
            # But only if it's still a string/UUID. Since we can't easily check type,
            # we check if the index exists or if we've already done this.
            # Usually, if we already have the index but it's the wrong type, we might have issues.
            # But here, let's just be careful.
            
            # If created_by is in columns, we check if we need to swap it.
            # Since SQLite doesn't support easy type checking via inspector for all cases,
            # we'll assume if we already have the index ix_contracts_v1_created_by, we might have finished.
            
            # Actually, let's just use try/except for the index or check existence.
            if 'ix_contracts_v1_created_by' in indices:
                batch_op.drop_index('ix_contracts_v1_created_by')
            
            if 'created_by' in columns:
                batch_op.drop_column('created_by')
            
            batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
            batch_op.create_index(batch_op.f('ix_contracts_v1_created_by'), ['created_by'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts_v1', schema=None) as batch_op:
        batch_op.drop_column('created_by')
        batch_op.add_column(sa.Column('created_by', sa.Uuid(), nullable=True))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_uuid'))
        batch_op.drop_column('entity_uuid')

    # ### end Alembic commands ###
