"""Fix Contract User ID and Audit Log

Revision ID: 406935f9448d
Revises: 7e0f57e495a3
Create Date: 2026-02-02 10:20:05.416276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406935f9448d'
down_revision: Union[str, None] = '7e0f57e495a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_uuid', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_uuid'), ['entity_uuid'], unique=False)

    with op.batch_alter_table('contracts_v1', schema=None) as batch_op:
        batch_op.drop_column('created_by')
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contracts_v1_created_by'), ['created_by'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts_v1', schema=None) as batch_op:
        batch_op.drop_column('created_by')
        batch_op.add_column(sa.Column('created_by', sa.UUID(), nullable=True))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_uuid'))
        batch_op.drop_column('entity_uuid')

    # ### end Alembic commands ###
