"""add_org_scoping_to_catalog

Revision ID: 44735e1b0d2b
Revises: 2236b5c5c373
Create Date: 2026-02-03 23:23:30.542576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44735e1b0d2b'
down_revision: Union[str, None] = '2236b5c5c373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    is_pg = op.get_bind().dialect.name == 'postgresql'
    bool_false = 'false' if is_pg else '0'

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Uuid(), nullable=False, server_default='00000000000000000000000000000001'))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text(bool_false)))
        batch_op.create_index(batch_op.f('ix_artists_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Uuid(), nullable=False, server_default='00000000000000000000000000000001'))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text(bool_false)))
        batch_op.create_index(batch_op.f('ix_releases_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Uuid(), nullable=False, server_default='00000000000000000000000000000001'))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text(bool_false)))
        batch_op.create_index(batch_op.f('ix_works_organization_id'), ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_works_organization_id'))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_releases_organization_id'))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artists_organization_id'))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('organization_id')
    # ### end Alembic commands ###
