"""Add Contract V1 tables

Revision ID: 7e0f57e495a3
Revises: fed736b8485d
Create Date: 2026-02-02 10:11:26.472738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e0f57e495a3'
down_revision: Union[str, None] = 'fed736b8485d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_type'), ['type'], unique=False)

    op.create_table('contracts_v1',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('territory', sa.String(length=255), nullable=True),
    sa.Column('exclusivity', sa.Boolean(), nullable=True),
    sa.Column('royalty_description', sa.Text(), nullable=True),
    sa.Column('advances_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('advances_currency', sa.String(length=3), nullable=True),
    sa.Column('recoupment_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts_v1', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_v1_created_by'), ['created_by'], unique=False)
        batch_op.create_index('ix_contracts_v1_org_number', ['organization_id', 'contract_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_contracts_v1_organization_id'), ['organization_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)

    op.create_table('contract_assets_v1',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts_v1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_assets_v1', schema=None) as batch_op:
        batch_op.create_index('ix_contract_assets_v1_org_contract', ['organization_id', 'contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_assets_v1_organization_id'), ['organization_id'], unique=False)

    op.create_table('contract_documents_v1',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts_v1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_documents_v1', schema=None) as batch_op:
        batch_op.create_index('ix_contract_documents_v1_org_contract', ['organization_id', 'contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_documents_v1_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_contract_documents_v1_unique_version', ['contract_id', 'version'], unique=True)

    op.create_table('contract_parties_v1',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('external_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('split_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('(entity_id IS NOT NULL) OR (external_name IS NOT NULL)', name='check_party_entity_or_name'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts_v1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_parties_v1', schema=None) as batch_op:
        batch_op.create_index('ix_contract_parties_v1_org_contract', ['organization_id', 'contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_parties_v1_organization_id'), ['organization_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_title'), ['title'], unique=False)

    pass # op.drop_table('distributors')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(length=100), nullable=True))

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('work_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('release_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('contact_ids', sa.JSON(), nullable=True))
        batch_op.drop_index('ix_contracts_contract_id')
        batch_op.drop_column('royalty_rate')
        batch_op.drop_column('terms')
        batch_op.drop_column('contract_id')
        batch_op.drop_column('is_template')

    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_person', sa.String(length=255), nullable=True))

    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_person', sa.String(length=255), nullable=True))

    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('credits', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(None, 'companies', ['distributor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('releases_distributor_id_fkey', 'distributors', ['distributor_id'], ['id'])
        batch_op.drop_column('credits')
        batch_op.drop_column('artist_ids')

    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.drop_column('contact_person')

    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_column('contact_person')
        batch_op.drop_column('logo_url')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_template', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contract_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('terms', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('royalty_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
        batch_op.create_index('ix_contracts_contract_id', ['contract_id'], unique=True)
        batch_op.drop_column('contact_ids')
        batch_op.drop_column('release_ids')
        batch_op.drop_column('work_ids')
        batch_op.drop_column('artist_ids')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('nationality')

    op.create_table('distributors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='distributors_pkey')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_title'))
        batch_op.drop_index(batch_op.f('ix_tasks_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('contract_parties_v1', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_parties_v1_organization_id'))
        batch_op.drop_index('ix_contract_parties_v1_org_contract')

    op.drop_table('contract_parties_v1')
    with op.batch_alter_table('contract_documents_v1', schema=None) as batch_op:
        batch_op.drop_index('ix_contract_documents_v1_unique_version')
        batch_op.drop_index(batch_op.f('ix_contract_documents_v1_organization_id'))
        batch_op.drop_index('ix_contract_documents_v1_org_contract')

    op.drop_table('contract_documents_v1')
    with op.batch_alter_table('contract_assets_v1', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_assets_v1_organization_id'))
        batch_op.drop_index('ix_contract_assets_v1_org_contract')

    op.drop_table('contract_assets_v1')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_email'))

    op.drop_table('contacts')
    with op.batch_alter_table('contracts_v1', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_v1_organization_id'))
        batch_op.drop_index('ix_contracts_v1_org_number')
        batch_op.drop_index(batch_op.f('ix_contracts_v1_created_by'))

    op.drop_table('contracts_v1')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_type'))
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.drop_index(batch_op.f('ix_companies_id'))

    op.drop_table('companies')
    # ### end Alembic commands ###
