"""Add status_quo_override

Revision ID: 815fda7f11d3
Revises: 4053a2735f7d
Create Date: 2026-02-04 22:06:16.330548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815fda7f11d3'
down_revision: Union[str, None] = '4053a2735f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_index('ix_distributors_id')
        batch_op.drop_index('ix_distributors_name')

    op.drop_table('distributors')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_index(batch_op.f('ix_artists_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_quo_override', sa.String(length=50), nullable=True))

    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_index(batch_op.f('ix_releases_catalog_number'), ['catalog_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_releases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_releases_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_releases_release_id'), ['release_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_releases_title'), ['title'], unique=False)

    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_index(batch_op.f('ix_works_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_work_id'), ['work_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_works_work_id'))
        batch_op.drop_index(batch_op.f('ix_works_title'))
        batch_op.drop_index(batch_op.f('ix_works_organization_id'))
        batch_op.drop_index(batch_op.f('ix_works_id'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_releases_title'))
        batch_op.drop_index(batch_op.f('ix_releases_release_id'))
        batch_op.drop_index(batch_op.f('ix_releases_organization_id'))
        batch_op.drop_index(batch_op.f('ix_releases_id'))
        batch_op.drop_index(batch_op.f('ix_releases_catalog_number'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('status_quo_override')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artists_organization_id'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    op.create_table('distributors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.create_index('ix_distributors_name', ['name'], unique=False)
        batch_op.create_index('ix_distributors_id', ['id'], unique=False)

    # ### end Alembic commands ###
