"""add_ai_contract_resolution_tables

Revision ID: d617c9d5cf5d
Revises: 1b8bbe8cb2e9
Create Date: 2026-02-15 19:03:59.556343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd617c9d5cf5d'
down_revision: Union[str, None] = '1b8bbe8cb2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_contract_resolution_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contract_hash', sa.String(length=64), nullable=False),
    sa.Column('extractor_version', sa.String(length=50), nullable=True),
    sa.Column('linker_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_contract_resolution_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_contract_resolution_runs_contract_hash'), ['contract_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_contract_resolution_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_contract_resolution_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_contract_resolution_runs_organization_id'), ['organization_id'], unique=False)

    op.create_table('ai_contract_resolution_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['ai_contract_resolution_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_contract_resolution_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_contract_resolution_links_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_contract_resolution_links_run_id'), ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_contract_resolution_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_contract_resolution_links_run_id'))
        batch_op.drop_index(batch_op.f('ix_ai_contract_resolution_links_id'))

    op.drop_table('ai_contract_resolution_links')
    with op.batch_alter_table('ai_contract_resolution_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_contract_resolution_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ai_contract_resolution_runs_id'))
        batch_op.drop_index(batch_op.f('ix_ai_contract_resolution_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_contract_resolution_runs_contract_hash'))

    op.drop_table('ai_contract_resolution_runs')
    # ### end Alembic commands ###
