"""v1.0.1 schema updates

Revision ID: fed736b8485d
Revises: 7c9f40c7bb4d
Create Date: 2026-01-30 15:04:02.674391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed736b8485d'
down_revision: Union[str, None] = '7c9f40c7bb4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.add_column(sa.Column('catalog_number', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_releases_catalog_number'), ['catalog_number'], unique=True)
        # batch_op.create_index(batch_op.f('ix_releases_id'), ['id'], unique=False)
        # batch_op.create_index(batch_op.f('ix_releases_release_id'), ['release_id'], unique=True)
        # batch_op.create_index(batch_op.f('ix_releases_title'), ['title'], unique=False)

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('credits')

    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_releases_title'))
        batch_op.drop_index(batch_op.f('ix_releases_release_id'))
        batch_op.drop_index(batch_op.f('ix_releases_id'))
        batch_op.drop_index(batch_op.f('ix_releases_catalog_number'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
